// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQjH-E0Z-60TlWf9gwJVcP1vQZVFxsNLs',
    appId: '1:400341750100:web:b0f8be6105ee8e8207b8c1',
    messagingSenderId: '400341750100',
    projectId: 'habit-tracker-aecb5',
    authDomain: 'habit-tracker-aecb5.firebaseapp.com',
    storageBucket: 'habit-tracker-aecb5.firebasestorage.app',
    measurementId: 'G-MVEBVR1J2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeMUGqXpPZHHtYGVRITmd0pEy_ktG305E',
    appId: '1:400341750100:android:ebaecc51806ce76007b8c1',
    messagingSenderId: '400341750100',
    projectId: 'habit-tracker-aecb5',
    storageBucket: 'habit-tracker-aecb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBShRz2UODTtFf85KTGK0bcCKymc--iXQQ',
    appId: '1:400341750100:ios:8c0f0d20ee8a565407b8c1',
    messagingSenderId: '400341750100',
    projectId: 'habit-tracker-aecb5',
    storageBucket: 'habit-tracker-aecb5.firebasestorage.app',
    iosBundleId: 'com.example.untitled7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBShRz2UODTtFf85KTGK0bcCKymc--iXQQ',
    appId: '1:400341750100:ios:8c0f0d20ee8a565407b8c1',
    messagingSenderId: '400341750100',
    projectId: 'habit-tracker-aecb5',
    storageBucket: 'habit-tracker-aecb5.firebasestorage.app',
    iosBundleId: 'com.example.untitled7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQjH-E0Z-60TlWf9gwJVcP1vQZVFxsNLs',
    appId: '1:400341750100:web:23b78c36fd055ba607b8c1',
    messagingSenderId: '400341750100',
    projectId: 'habit-tracker-aecb5',
    authDomain: 'habit-tracker-aecb5.firebaseapp.com',
    storageBucket: 'habit-tracker-aecb5.firebasestorage.app',
    measurementId: 'G-JNMHC77G38',
  );
}
